version: '3.7'

services:
  chat-gpt:
    container_name: chat-gpt-discord-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/chat-gpt-discord-bot:/app/config
    restart: always
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: '0.1'
  chat-gpt-terminal:
    container_name: chat-gpt-discord-terminal
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/chat-gpt-discord-terminal:/app/config
    restart: always
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: '0.1'
