version: '3.7'

services:
  chatgpt-discord-bot:
    container_name: chatgpt-discord-bot
    image: ghcr.io/zloy-roma/chatgpt-discord-bot:3.0.0
    volumes:
      - type: bind
        source: ./keys
        target: /app/keys
    restart: always
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.5'
