name: Build

on:
  push:
    branches:
      - master
    paths:
      - package.json
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  test:
    uses: zloy-roma/chatgpt-discord-bot/.github/workflows/test.yml@master
  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version and name from package.json
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.deploy/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.VERSION }}
