name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  push:
    name: "chat-gpt-discord"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.8.2"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ghcr.io/${{ github.actor }}/chat-gpt-discord-bot
          cache-from: type=gha
          cache-to: type=gha,mode=max