name: Test

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Test eslint
        run: yarn lint

      - name: Test typescript
        run: tsc -b

      - name: Test build
        run: yarn build
